version: 1.0.{build}
branches:
  only:
  - release
skip_tags: true
clone_depth: 50
environment:
  nodejs_version: 12.0.0
image: ubuntu
stack: node $nodejs_version

init:
  - ps: Update-AppveyorBuild -Version "$(Get-Date -format yyyy.M.d).$env:APPVEYOR_BUILD_NUMBER"

install:
  - npm install

before_build:
  - node --version

build_script:
  - npm run build

test_script:
  - npm run test_for_build_server
